config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "posts#index"

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  
    resources :posts do
      member do
        patch :change_status
      end
    end

    namespace :admin do
      resources :users do
        member do
          patch :change_authority
        end
      end
      resources :banners

      resources :dashboard
    end
    get '/switch_locale', to: 'application#switch_locale', as: :switch_locale
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  

  # post '/set_language', to: 'application#set_language', as: :set_language
 

end

app/models/admin/banner.rb
class Admin::Banner < ApplicationRecord
    has_one_attached :image
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < ApplicationController
  before_action :set_admin_banner, only: %i[ show edit update destroy ]

  # GET /admin/banners or /admin/banners.json
  def index
    @admin_banners = Admin::Banner.all
  end

  # GET /admin/banners/1 or /admin/banners/1.json
  def show
  end

  # GET /admin/banners/new
  def new
    @admin_banner = Admin::Banner.new
  end

  # GET /admin/banners/1/edit
  def edit
  end

  # POST /admin/banners or /admin/banners.json
  def create
    @admin_banner = Admin::Banner.new(admin_banner_params)

    respond_to do |format|
      if @admin_banner.save
        format.html { redirect_to admin_banner_url(@admin_banner), notice: "Banner was successfully created." }
        format.json { render :show, status: :created, location: @admin_banner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/banners/1 or /admin/banners/1.json
  def update
    respond_to do |format|
      if @admin_banner.update(admin_banner_params)
        format.html { redirect_to admin_banner_url(@admin_banner), notice: "Banner was successfully updated." }
        format.json { render :show, status: :ok, location: @admin_banner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/banners/1 or /admin/banners/1.json
  def destroy
    @admin_banner.destroy!

    respond_to do |format|
      format.html { redirect_to admin_banners_url, notice: "Banner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_banner
      @admin_banner = Admin::Banner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_banner_params
      params.require(:admin_banner).permit(:name, :link, :image)
    end
end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/views/admin/banners/_banner.html.erb
<div class="card post-card  border" id="<%= dom_id banner %>">
  <% if banner && banner.image.attached? %>
  <%= image_tag banner.image , alt: "cover_banner", style: "width: 100%; height: 250px;", class: "object-fit-cover"%>
  <% end %>  

  <div class="card-body p-2 h-100">
    <h2 class="card-title fs-4"> <%= banner.name%></h2>
  </div>

</div>

app/views/admin/banners/_form.html.erb
<%= form_with(model: admin_banner) do |form| %>
  <% if admin_banner.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_banner.errors.count, "error") %> prohibited this admin_banner from being saved:</h2>

      <ul>
        <% admin_banner.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-2">
    <%= form.label :name ,class: "form-label" %>
    <span class="mark-required"> * </span>
    <%= form.text_field :name, class: "form-control", required: true%>
  </div>
  <div class="field mb-2">
    <%= form.label :link,class: "form-label" %>
    <%= form.text_field :link , class: "form-control", required: true%>
  </div>
  <div class="field mb-2">
    <%= form.label :image, class: "form-label" %>
    <span class="mark-required"> * </span>
    <%= form.file_field :image, class: "form-control", required: true%>
  </div>
  <div>
   
  </div>
  <p class="mark-required f-s"><%=  t('global.post.required_fields_message')%></p>

  <div>
    <%= form.submit t('global.banner.new_banner') , class: "btn btn-primary btn-sm"%>
  </div>
<% end %>

app/views/admin/banners/edit.html.erb
<h1>Editing banner</h1>

<%= render "form", admin_banner: @admin_banner %>

<br>

<div>
  <%= link_to "Show this banner", @admin_banner %> |
  <%= link_to "Back to banners", admin_banners_path %>
</div>

app/views/admin/banners/index.html.erb
<div class="container"> 
  <p style="color: green"><%= notice %></p>
  <div class=" d-flex align-items-center flex-column mb-4">
    <h1 class="fs-2">Banners</h1>

    <%= link_to t('global.banner.create_banner'), new_admin_banner_path, method: "get", class: ""%>

    <div id="admin_banners" class="d-flex align-items-stretch">
      <% @admin_banners.each do |admin_banner| %>
          <%= link_to admin_banner_path(admin_banner) , class: "col-3 me-2 text-decoration-none" do %>
              <%= render admin_banner %>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/banners/new.html.erb
<div class="container"> 

  <div class="d-flex d-flex justify-content-between" >
    <h1> <%= t("global.banner.new_banner") %>  </h1>
    <%= link_to t("global.post.back_to_banners"), admin_banners_path ,class:"btn btn-outline-dark btn-sm custom-height align-self-center"%>
  </div>
  
  <%= render "form", admin_banner: @admin_banner %>

  <br>
</div>

app/views/admin/banners/show.html.erb
<div class="container">
  <% if notice %>
  <div class="notice alert alert-success mt-2 lert-dismissible fade show d-flex justify-content-between" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>

  <div class="d-flex justify-content-between mb-3">
    <h2 class="card-title fs-3"> <%= @admin_banner.name%></h2>
    <%= link_to t('global.banner.back_to_banners'), admin_banners_path, method: "get", class:"btn btn-outline-dark btn-sm custom-height"%>
  </div>
    <div>
      <% if @admin_banner.image.attached? %>
        <%= image_tag @admin_banner.image , alt: "cover_banner", style: "width: 100%; height: 30rem;"%>
      <% end %> 
      <p class="text-card"><%= @admin_banner.link %></p>

      <table class="table">
        <tr>
          <th><%= t ("global.banner.created_by") %></th>
          <td> </td>
          <th><%= t ("global.post.created_at") %> </th>
          <td>  </td>
        </tr>
      </table>
      <%= link_to t('global.post.edit'), edit_admin_banner_path(id: @admin_banner.id), method: "get" , class: "btn btn-primary btn-sm me-2" %> |
      <%= button_to t('global.banner.delete'), @admin_banner, method: "delete", data: {turbo_confirm: 'Are you sure? '}, class: "btn btn-danger btn-sm" %>
    </div>



</div>