config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "posts#index"

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  
    resources :posts do
      member do
        patch :change_status
      end
    end

    namespace :admin do
      resources :users do
        member do
          patch :change_authority
        end
      end
      resources :banners

      resources :dashboard
    end
    get '/switch_locale', to: 'application#switch_locale', as: :switch_locale
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  

  # post '/set_language', to: 'application#set_language', as: :set_language
 

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
    
    def index
    end  
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/index.html.erb
<div class="container">
  <h1> Page management</h1>

  <div>
    <p>Users</p>
    <%= button_to 'Users list', admin_users_path , method: "get" , class: "btn btn-primary btn-sm m-2"%>
  </div>

  <div>
    <p>Bannars</p>
    <%= button_to 'Bannar list', admin_banners_path , method: "get" , class: "btn btn-primary btn-sm m-2"%>

  </div>

  <div>
    <p>Contact us</p>
    <%= link_to 'contact us', url_for(controller: '/posts', action: 'index', post_type: "contact_us") , method: "get", class:"btn btn-primary custom-height "%>

  </div>
</div>