config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "posts#index"

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  
    resources :posts do
      member do
        patch :change_status
      end
    end

    namespace :admin do
      resources :users do
        member do
          patch :change_authority
        end
      end
      resources :banners

      resources :dashboard
    end
    get '/switch_locale', to: 'application#switch_locale', as: :switch_locale
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  

  # post '/set_language', to: 'application#set_language', as: :set_language
 

end

app/views/shared/_bannar.html.erb
<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel" data-bs-interval="3000">
  <div class="carousel-inner">
    <% @banners.each_with_index do |banner, index| %>
      <div class="carousel-item <%= 'active' if index == 0 %>" >
          <%= image_tag banner.image, alt: "Example Image", class: "d-block w-100"%>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_footer.html.erb
<footer class="mt-2 footer">
 
  <div class="d-flex flex-column">
      <div class="row mt-3">
        <div class="col-4">
          <h5 class="text-color"> <%= t("global.navbar.about_us") %></h5>
          <p>An IT consultancy can help you assess your technology needs and develop a technology strategy.</p>
        </div>
        <div class="col-4">
          <h5 class="text-color"> Links</h5>
          <ul class="list-unstyled ">
            <li>
              <%= link_to t('global.navbar.products'), posts_path(post_type: "products"), class: "nav-link active a-footer" %>
            </li>
            <li>
              <%= link_to t('global.navbar.projects'), posts_path(post_type: "projects"), class: "nav-link active a-footer" %>
            </li>
            <li>
              <%= link_to t('global.navbar.services'), posts_path(post_type: "services"), class: "nav-link active a-footer" %>
            </li>
            <li> 
              <%= link_to t('global.navbar.contact_us'), posts_path(post_type: "contact_us"), class: "nav-link active a-footer" %>
            </li>
          </ul>
        </div>
        <div class="col-4 ">
          <h5 class="text-color"> <%= t("global.home.our_services") %></h5>
          <div class="d-flex">
              <% if @services_posts %>
                <% @services_posts.each do |post| %>
                  <%= link_to post_path(post) , class: "text-decoration-none p-0 m-0 pe-1" do %>
                    <div class=""  id="<%= dom_id post %>">    
                      <% if post && post.image.attached? %>
                        <%= image_tag post.image , alt: "cover_post", style: "width: 100px; height: 100px;", class: "object-fit-cover"%>
                      <% end %>   
                    </div>
                  <% end %>
                <% end %>
              <% end %> 
          </div>
        </div>
    </div>
    <div class="row text-center">
      <p class="p-0 m-0"><%= t('global.footer.copy_right')%> </p>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="border-bottom-header mb-2"> 
  <nav class="navbar navbar-expand-lg navbar-light header container">
    <div class="container-fluid">
      <%= link_to image_tag("logo.png", alt: "" , class: "site-logo"), posts_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to t('global.navbar.home'), posts_path, class: "nav-link active " %>
          </li>
          <li class="nav-item">
            <%= link_to t('global.navbar.products'), posts_path(post_type: "products"), class: "nav-link active " %>
          </li>
          <li class="nav-item">
            <%= link_to t('global.navbar.projects'), posts_path(post_type: "projects"), class: "nav-link active " %>
          </li>
          <li class="nav-item">
            <%= link_to t('global.navbar.services'), posts_path(post_type: "services"), class: "nav-link active " %>
          </li>
          <li class="nav-item">
            <%= link_to t('global.navbar.contact_us'), posts_path(post_type: "contact_us"), class: "nav-link active" %>
          </li>
          <li class="nav-item">
          <%= link_to t('global.navbar.about_us'), posts_path(post_type: "about_us"), class: "nav-link active " %>
  
          </li>
          <% if user_signed_in? && current_user.authority == "admin" %>
            <li class="nav-item">
              <%= link_to t('global.navbar.dashboard'), admin_dashboard_index_path, class: "nav-link active" %>
            </li>
          <% end %>
            <% I18n.available_locales.each do |locale| %>
              <li class="nav-link active">
                <% if I18n.locale == locale %>
                  <%= t(locale, scope: 'global.navbar') %> 
                <% else %>
                  <%= link_to t(locale, scope: 'global.navbar'), url_for(locale: locale, params: request.query_parameters) %>
                <% end %>
              </li>
            <% end %>
        
        </ul>
      </div>
      <div>
      <% if user_signed_in? %>
        <%= button_to t('global.navbar.log_out'), destroy_user_session_path, method: :delete, class:"btn btn-outline-dark btn-sm"%>
      <% else %> 
      <%= link_to t('global.navbar.log_in'), new_user_session_path , class:"btn btn-outline-dark btn-sm"%>
      <%= link_to t('global.navbar.sign_up'), new_user_registration_path , class:"btn btn-primary btn-sm"%>
      <% end %>
    </div>
    </div>
  </nav>
</header>