config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "posts#index"

    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  
    resources :posts do
      member do
        patch :change_status
      end
    end

    namespace :admin do
      resources :users do
        member do
          patch :change_authority
        end
      end
      resources :banners

      resources :dashboard
    end
    get '/switch_locale', to: 'application#switch_locale', as: :switch_locale
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  

  # post '/set_language', to: 'application#set_language', as: :set_language
 

end

app/models/post.rb
class Post < ApplicationRecord
    
    belongs_to :user
    has_one_attached :image
    has_rich_text :content_ar
    has_rich_text :content_en

    validates :title_ar, presence: true
    validates :content_ar, presence: true 
    validates :image, presence: true

    def self.ransackable_attributes(auth_object = nil)
        %w(status)
        # ["image_attachment", "image_blob", "rich_text_content_ar", "rich_text_content_en", "user"]
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :home
  # before_action :authenticate_user!, except: [ :index, :show]
  load_and_authorize_resource

  PUBLISHED = "published"
  UNPUBLISHED = "unpublished"

  # GET /posts or /posts.json
  def index
    puts params
    # @post_type= params[:post_type]
    # @q = Post.ransack(params[:q])
    @post_type= params[:post_type]

    if(params[:status].present? )
      @status = params[:status ]
    else
      @status = [PUBLISHED, UNPUBLISHED]
    end

    @status_options = [["All", ""], ["Published", "published"], ["Unpublished", "unpublished"]]
    if @post_type
      if(!user_signed_in? || (user_signed_in? && current_user.authority == 'visitor'))
        @posts = Post.where(post_type: @post_type, status: PUBLISHED)
      else
        @posts = Post.where(post_type: @post_type, status: @status)
      end
      set_meta_tags title: t("global.navbar.#{@post_type}")
    end
  end
  
  # Get Home 
  def home
    @products_posts = Post.where(post_type: "products", status: PUBLISHED).limit(3)
    @services_posts = Post.where(post_type: "services" , status: PUBLISHED).limit(3)
    @projects_posts = Post.where(post_type: "projects", status: PUBLISHED).limit(3)
  end

  # GET /posts/1 or /posts/1.json
  def show 
    set_meta_tags title: @post.title_ar
                  
  end

  # GET /posts/new
  def new
    @post_type = params[:post_type]
    @post = Post.new
    render
  end

  # GET /posts/1/edit
  def edit
    @post_type = params[:post_type]
    @post = Post.find_by(id: params[:id])   
  end

  # POST /posts or /posts.json
  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    @post.status = UNPUBLISHED
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(id: @post.id), notice: I18n.t("global.post.post_created_successfully")}
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    @post.status = UNPUBLISHED
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: I18n.t("global.post.post_updated_success" )}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    post_type = @post.post_type
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url(post_type: post_type), notice: I18n.t("global.post.post_destroy_message") }
      format.json { head :no_content }
    end
  end 

  def change_status
    @post = set_post
    if @post.update(status: params[:status])
      redirect_to post_url(@post), notice: I18n.t("global.post.change_post_status_success")
    else
      redirect_to post_url(@post), alert: I18n.t("global.post.change_post_status_failed")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title_ar, :title_en, :content_ar, :content_en, :post_type, :status, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-2">
    <%= form.label :title_ar ,class: "form-label" %>
    <span class="mark-required"> * </span>
    <%= form.text_field :title_ar , class: "form-control", required: true%>
  </div>
  <div class="field mb-2">
    <%= form.label :title_en,class: "form-label" %>
    <%= form.text_field :title_en , class: "form-control"%>
  </div>
  <div class="field mb-2">
    <%= form.label :content_ar, class: "form-label" %>
    <span class="mark-required"> * </span>
    <%= form.rich_text_area :content_ar, class: "form-control" , required: true%>
  </div>
  <%= form.hidden_field :post_type, value: @post_type %>

  <div class="field mb-2">
    <%= form.label :content_en, class: "form-label" %>
    <%= form.rich_text_area :content_en, class: "form-control" %>
  </div>
  <%if @post.persisted? %>
    <%= image_tag @post.image, alt: "Example Image", class: "img-fluid", style: "width: 300px; height: 300px;"%>
    <div class="field mb-2">
      <%= form.label :image, class: "form-label" %>
      <span class="mark-required"> * </span>
      <%= form.file_field :image, class: "form-control"%>
    </div>
  <% else %>
    <div class="field mb-2">
      <%= form.label :image, class: "form-label" %>
      <span class="mark-required"> * </span>
      <%= form.file_field :image, class: "form-control", required: true%>
    </div>
  <% end %>
  <p class="mark-required f-s"><%=  t('global.post.required_fields_message')%></p>
  <div>
    <% if @post.persisted? %>
      <%= form.submit t('global.post.edit_post'), class: "btn btn-primary btn-sm" %>
    <% else %>
      <%= form.submit t('global.post.create_post'), class: "btn btn-primary btn-sm" %>
    <% end %> 
  </div>
<% end %>

app/views/posts/_home.html.erb
 
<%= render partial: "shared/bannar" %>

<div class="container">
  <div>
    <div class="text-center mt-7">
      <span class="text-color"><%=  t('global.home.quick_steps')%> </span>
      <h3> <%=  t('global.home.our_work_feature')%>  </h3>
      <div class="row mt-4">
        <div class="col-4 d-flex">
          <div class="service-four-number"> 01</div>
          <div class="text-start ms-3">
            <h4><%= t('global.home.project_discussion') %></h4>
            <p> <%= t('global.home.project_discussion_desc') %></p>
          </div>
        </div>
        <div class="col-4 d-flex" >
          <div class="service-four-number"> 02</div>
          <div class="text-start ms-3">
            <h4><%= t('global.home.testing_trying') %></h4>
            <p> <%= t('global.home.project_discussion_desc') %></p>
          </div>
        </div>
        <div class="col-4 d-flex">
          <div class="service-four-number"> 03</div>
          <div class="text-start ms-3">
            <h4><%= t('global.home.execute_install') %></h4>
            <p> <%= t('global.home.project_discussion_desc') %></p>
          </div>
        </div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
  <% if !@services_posts.empty? %>
    <div class="row mt-7">
      <div class="col-3 ">
        <span class="text-color"><%= t("global.home.our_services") %> </span>
        <h3><%= t("global.home.our_best_services") %></h3>
        <p><%= t("global.home.service_provider") %></p>
        <%= link_to t("global.home.learn_more"), url_for(controller: 'posts', action: 'index', post_type: "services") , method: "get", class:"btn btn-primary custom-height "%>
      </div>
      <div class="col-9">
        <div class="row">
          <% @services_posts.each do |post| %>
            <%= link_to post_path(post) , class: "col-4 text-decoration-none p-0 m-0 pe-1" do %>
            <div class="card post-card shadow rounded border-0 "  id="<%= dom_id post %>">    
              <% if post && post.image.attached? %>
                <%= image_tag post.image , alt: "cover_post", style: "width: 100%; height: 230px;", class: "object-fit-cover"%>
              <% end %>   
              <div class="card-body p-2 h-100">
                <div class="d-flex ">
                  <% if I18n.locale == :en %>
                    <h2 class=" col-12 card-title fs-5 text-center"> <%= post.title_en.present? ? post.title_en : post.title_ar%></h2>
                  <% else %>
                    <h2 class=" col-12 card-title fs-5 text-center"> <%= post.title_ar%></h2>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="team-member">
    <div class="mt-7 text-center">
      <span class="text-color"><%= t("global.home.team_members")%></span>
      <h3><%= t("global.home.our_top_skilled_experts")%></h3>
    </div>
    <div class="row d-flex justify-content-center"> 
     <div class="col-3 text-center">
      <%= image_tag "person-icon.jpg" , alt: "cover_post", style: "width: 50%; height: 200px;", class: ""%>
      <h3> Shuaib zahidi</h3>
      <p>Manager</p>
     </div>
     <div class="col-3 text-center">
      <%= image_tag "person-icon.jpg" , alt: "cover_post", style: "width: 50%; height: 200px;", class: ""%>
      <h3> Shuaib zahidi</h3>
      <p>Manager</p>
     </div>
     <div class="col-3 text-center">
      <%= image_tag "person-icon.jpg" , alt: "cover_post", style: "width: 50%; height: 200px;", class: ""%>
      <h3> Shuaib zahidi</h3>
      <p>Manager</p>
     </div>
    </div>
  </div>


</div>

app/views/posts/_pages.html.erb
<div class="container">
   <div class=row>
    <div class="col">
     <%= image_tag post.image , alt: "cover_post", style: "width: 100%; height: 20rem;"%>

    </div>
    <div class="col">
        <% if I18n.locale == :en %>
            <h2 class="card-title fs-3"> <%= post.title_en.present? ? post.title_en : post.title_ar%></h2>
        <% else %>
            <h2 class="card-title fs-3"> <%= post.title_ar%></h2>
        <% end %>

        <% if I18n.locale == :en %>
           <p class="text-card"><%= post.content_en.present? ? post.content_en : post.content_ar %></p>
        <% else %>
           <p class="text-card"><%= post.content_ar %></p>
        <% end %> 
    </div>
   </div>
  
 
</div>

app/views/posts/_post.html.erb
<div class="card post-card  border"  id="<%= dom_id post %>">    
    <% if post && post.image.attached? %>
      <%= image_tag post.image , alt: "cover_post", style: "width: 100%; height: 250px;", class: "object-fit-cover"%>
    <% end %>   
    
    <div class="card-body p-2 h-100">
    <div class="d-flex ">
      <% if I18n.locale == :en %>
        <h2 class="card-title fs-4"> <%= post.title_en.present? ? post.title_en : post.title_ar%></h2>
      <% else %>
        <h2 class="card-title fs-4"> <%= post.title_ar%></h2>
      <% end %>
    </div>
    
   
  </div>
  </div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="d-flex d-flex justify-content-between" >
    <h1 class="fs-2 mb-3"><%= t("global.post.edit_#{@post.post_type}")%></h1>
    <%= link_to t("global.post.back_to_posts"), posts_path(post_type: @post.post_type), method: "get" ,class:"btn btn-outline-dark btn-sm custom-height align-self-center"%>
  </div>

  <%= render "form", post: @post %>

  <br>

  <div>
    <%= link_to t('global.post.show_this_post'), @post %> 
  </div>
</div>

app/views/posts/index.html.erb
<% if notice %>
  <div class="notice alert alert-success mt-2 lert-dismissible fade show d-flex justify-content-between" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>


<% if @post_type.present? %>
  <div class="container">
    <div class=" d-flex align-items-center flex-column mb-4">
    
      <h1 class="fs-2"> <%= @post_type? t("global.navbar.#@post_type") : t("global.navbar.home") %></h1>
      <% if @post_type %>
        <p class="fs-6">
          <%= link_to(t('global.navbar.home'), posts_path ) %> - <%= link_to(t("global.navbar.#{@post_type}"), posts_path(post_type: @post_type)) %>
        </p>
      <% end %>    
    
      <% if user_signed_in? && (current_user.authority != "visitor") && @post_type != "contact_us" && @post_type != "about_us" %>
        <%= link_to t('global.post.create_post'), new_post_path(post_type: @post_type), method: "get", class: ""%>

        <div class="d-flex align-items-start w-100">
          <%= form_with url: posts_path(post_type: @post_type), method: :get , class: "d-flex justify-content-between" do |f| %>
            <div class=" d-flex flex-row">
              <%= f.select :status, options_for_select(@status_options), prompt: t('global.post.select_status'), class: "form-control" %>
              <%= f.hidden_field :post_type, value: @post_type %>
              <%= f.submit t('global.post.search'), class: "btn btn-primary btn-sm me-1" %>
            </div> 
          <% end %>
        </div>
      <% end %>
      </div>
  </div>
  <div class="container mt-2">
    <% if @posts.empty? %>
        <p class="text-center fs-4"> <%= t("global.post.no_#{@post_type}")  %> </p>
    <% else %>
      <% if @post_type == "contact_us" || @post_type == "about_us" %>
        <div class="d-flex justify-content-center">
          <%= render "pages", post: @posts[@posts.length() -1] %>
        </div>
      <% else %> 
        <div id="posts" class="d-flex  align-items-stretch">
          <% @posts.each do |post| %>
            <%= link_to post_path(post) , class: "col-3 text-decoration-none" do %>
              <%= render post %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
  
<% else %> 
  <%= render partial: "home" %>
<% end %> 

app/views/posts/new.html.erb
<div class="container">
  <div class="d-flex d-flex justify-content-between" >
    <h1> <%= t("global.post.new_#{@post_type}") %>  </h1>
    <%= link_to t("global.post.back_to_posts"), posts_path ,class:"btn btn-outline-dark btn-sm custom-height align-self-center"%>
  </div>
  <%= render "form", post: @post %>
  <br>
  
</div>

app/views/posts/show.html.erb
<% if notice %>
  <div class="notice alert alert-success mt-2 lert-dismissible fade show d-flex justify-content-between" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>
<div class="container"> 
  <div class="d-flex justify-content-between mb-3">
    <% if I18n.locale == :en %>
      <h2 class="card-title fs-3"> <%= @post.title_en.present? ? @post.title_en : @post.title_ar%></h2>
    <% else %>
      <h2 class="card-title fs-3"> <%= @post.title_ar%></h2>
    <% end %>
    <%= link_to t('global.post.back_to_posts'), posts_path(post_type: @post.post_type), method: "get", class:"btn btn-outline-dark btn-sm custom-height"%>
  </div> 
  <div>
    <% if @post.image.attached? %>
      <%= image_tag @post.image , alt: "cover_post", style: "width: 100%; height: 30rem;"%>
    <% end %> 
  </div>

  <% if I18n.locale == :en %>
    <p class="text-card"><%= @post.content_en.present? ? @post.content_en : @post.content_ar %></p>
  <% else %>
    <p class="text-card"><%= @post.content_ar %></p>
  <% end %> 
  <hr>
  <% if user_signed_in? && (current_user.authority != "visitor")%>
    
    <table class="table">
      <tr>
        <th><%= t ("global.post.created_by") %></th>
        <td> <%= @post.user.email%> </td>
        <th><%= t ("global.post.created_at") %> </th>
        <td> <%=@post.created_at.strftime('%m/%d/%Y')%> </td>
      </tr>
      <tr>
        <th><%= t ("global.post.post_status") %></th>
        <td><%= t("global.post.#{@post.status}")%></td>
        <th> <%= t ("global.post.post_type") %> </th>
        <td><%= t("global.post.#{@post.post_type}") %></td>
      </tr>
    </table>
  <%  end %>
  <% if user_signed_in? && (current_user.authority == "admin" || current_user.authority == "staff" )%>
    <div class="d-flex">
      <% if @post.status != 'published' %> 
        <%= button_to t('global.post.publish_this_post'), change_status_post_path(id: @post.id, status: "published"), method: "patch" , class: "btn btn-success"%> |
      <% else %>
        <%= button_to t('global.post.unpublish_this_post'), change_status_post_path(id: @post.id, status: "unpublished"), method: "patch",  class: "btn btn-success"%> |
      <% end %>
      <%= link_to t('global.post.edit'), edit_post_path(id: @post.id, post_type: @post.post_type), method: "get" , class: "btn btn-primary btn-sm me-2" %> |
      <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
        <%= t('global.post.delete') %>
      </button>
      </div>
  <% end %>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure? 
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= button_to t('global.post.delete'), @post, method: "delete", class: "btn btn-danger btn-sm" %>
      </div>
    </div>
  </div>
</div>